"""CYYC Apron 1 practice tables.

These values are transcribed from the supplied training-table images. Keep this
file as the source of truth: the browser loads it through /api/rules, so a chart
update only needs a data change here.
"""

# The two Arrival columns in the supplied tables are the north-flow (17) and
# south-flow (35) arrival columns. Departure answers are runway-specific.
# No gates outside the gate lists below are generated by the game.
GATE_RULES = [
    {
        "gates": "1–6, 12, 14, 16, 18, 20",
        "gateNumbers": [1, 2, 3, 4, 5, 6, 12, 14, 16, 18, 20],
        "arrival17": "HB",
        "dep17R": "K",
        "dep17L": "HB",
        "arrival35": "K",
        "dep35L": "HB",
        "dep35R": "HB",
    },
    {
        "gates": "21–24, 11, 13, 15, 17, 19",
        "gateNumbers": [11, 13, 15, 17, 19, 21, 22, 23, 24],
        "arrival17": "HB",
        "dep17R": "HB",
        "dep17L": "HB",
        "arrival35": "HB",
        "dep35L": "HB",
        "dep35R": "HB",
    },
    {
        "gates": "31–40, 50, 52, 54, 56, 58",
        "gateNumbers": list(range(31, 41)) + [50, 52, 54, 56, 58],
        "arrival17": "HD",
        "dep17R": "G",
        "dep17L": "G",
        "arrival35": "HD",
        "dep35L": "G",
        "dep35R": "G",
    },
    {
        "gates": "51, 53, 55, 57, 59, 70–73, 76",
        "gateNumbers": [51, 53, 55, 57, 59, 70, 71, 72, 73, 76],
        "arrival17": "JT*",
        "dep17R": "G",
        "dep17L": "JS",
        "arrival35": "JS",
        "dep35L": "JT*",
        "dep35R": "E",
    },
    {
        "gates": "79, 78, 75, 74, 80/81, 84/85, 88/89, 92",
        "gateNumbers": [74, 75, 78, 79, 80, 81, 84, 85, 88, 89, 92],
        "arrival17": "EA/BA",
        "dep17R": "JR",
        "dep17L": "JR",
        "arrival35": "EA/BA",
        "dep35L": "JR",
        "dep35R": "JR",
    },
    {
        # The supplied image labels this pair as 86/86; 86 is therefore the
        # only gate from that pair added to the playable gate list.
        "gates": "82/83, 86/86, 90/91, 93, 94, 95",
        "gateNumbers": [82, 83, 86, 90, 91, 93, 94, 95],
        "arrival17": "BA**",
        "dep17R": "BC",
        "dep17L": "BC",
        "arrival35": "BA**",
        "dep35L": "BC",
        "dep35R": "BC",
    },
]

TAXIWAY_POSITIONS = [
    {"taxiway": "K", "positions": ["4", "5"]},
    {"taxiway": "HB", "positions": ["6", "7"]},
    {"taxiway": "HD", "positions": ["8", "9"]},
    {"taxiway": "G", "positions": ["10", "11"]},
    {"taxiway": "JT", "positions": ["14"]},
    {"taxiway": "JS", "positions": ["15"]},
    {"taxiway": "E", "positions": ["16"]},
    {"taxiway": "JR", "positions": ["17"]},
    {"taxiway": "EA", "positions": ["18", "19", "20"]},
    {"taxiway": "BA", "positions": ["21", "22"]},
    {"taxiway": "BC", "positions": ["23", "24"]},
]

# Four runways are used by the departure columns. Arrival uses the 17 or 35
# flow column, as shown in the supplied tables.
RUNWAYS = [
    {"name": "17R", "flow": "17", "tableKey": "dep17R", "arrivalLabel": "17R / 17L"},
    {"name": "17L", "flow": "17", "tableKey": "dep17L", "arrivalLabel": "17R / 17L"},
    {"name": "35L", "flow": "35", "tableKey": "dep35L", "arrivalLabel": "35L / 35R"},
    {"name": "35R", "flow": "35", "tableKey": "dep35R", "arrivalLabel": "35L / 35R"},
]

AIRPORT_RULES = {
    "airport": "CYYC",
    "apron": "Apron 1",
    "title": "Apron 1 gate, taxiway and position tables",
    "note": "Rules transcribed from the supplied Apron 1 training tables. Asterisks are retained from the source table; EA/BA accepts either listed taxiway.",
    "runways": RUNWAYS,
    "gateRules": GATE_RULES,
    "taxiwayPositions": TAXIWAY_POSITIONS,
    "taxiways": [row["taxiway"] for row in TAXIWAY_POSITIONS],
    "positions": [position for row in TAXIWAY_POSITIONS for position in row["positions"]],
}
